name: Pull Request Preview

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  create-deployment-preview:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initial Deployment Preview Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        id: pr-preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Building Deployment Preview..
            A preview of this Pull Request is being created. Hold tight while it's building ⚒️
            This comment will be automatically updated when the preview is ready.

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: npm install, build, and test
        env:
          REACT_APP_BASEURL: "https://osuscc-pr-${{ github.event.pull_request.number }}.azurewebsites.net"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: create .env file
        shell: bash
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          AIRNOW_API_KEY: ${{ secrets.AIRNOW_API_KEY }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo MONGO_DB_NAME="dev" >> .env
          echo MONGO_URL="$MONGODB_URL" >> .env
          echo OWM_API_KEY="$OWM_API_KEY" >> .env
          echo AIRNOW_API_KEY="$AIRNOW_API_KEY" >> .env
          echo JWT_SECRET="$JWT_SECRET" >> .env

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create PR Deployment Slot
        uses: Azure/cli@v1
        with:
          inlineScript: az webapp deployment slot create --name osuscc --resource-group capstone --slot pr-${{ github.event.pull_request.number }}

      - name: Update PR Preview Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ steps.pr-preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Deployment Preview
            😎 Preview this PR: https://osuscc-pr-${{ github.event.pull_request.number }}.azurewebsites.net
            🧑🏼‍💻 Commit SHA: ${{ github.sha }}
          reactions: "rocket"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "osuscc"
          slot-name: pr-${{ github.event.pull_request.number }}
          package: .

  update-deployment-preview:
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Find PR Preview Comment
        uses: peter-evans/find-comment@v1
        id: deploy-preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployment Preview

      - name: Update PR Preview Comment
        if: steps.deploy-preview-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ steps.deploy-preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Building Deployment Preview..
            The Pull Request preview is being updated. Hold tight while it's building ⚒️
            This comment will be automatically updated when the new version is ready.

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          REACT_APP_BASEURL: "https://osuscc-pr-${{ github.event.pull_request.number }}.azurewebsites.net"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: create .env file
        shell: bash
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          AIRNOW_API_KEY: ${{ secrets.AIRNOW_API_KEY }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        run: |
          echo MONGO_DB_NAME="dev" >> .env
          echo MONGO_URL="$MONGODB_URL" >> .env
          echo OWM_API_KEY="$OWM_API_KEY" >> .env
          echo AIRNOW_API_KEY="$AIRNOW_API_KEY" >> .env

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "osuscc"
          slot-name: pr-${{ github.event.pull_request.number }}
          package: .

      - name: Update PR Preview Comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ steps.deploy-preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Deployment Preview
            😎 Preview this PR: https://osuscc-pr-${{ github.event.pull_request.number }}.azurewebsites.net
            🧑🏼‍💻 Commit SHA: ${{ github.sha }}

  delete-deployment-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete PR Deployment Slot
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az webapp deployment slot delete --name osuscc --resource-group capstone --slot pr-${{ github.event.pull_request.number }}

      - name: Find PR Preview Comment
        uses: peter-evans/find-comment@v1
        id: deploy-preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployment Preview

      - name: Update PR Preview Comment
        if: steps.deploy-preview-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          comment-id: ${{ steps.deploy-preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Deployment Preview
            🏁 This PR has been closed. No deployment preview is available.
          reactions: "hooray"